#baseURL = "http://127.0.0.1:8040/"
baseURL =                          "https://magnetosphere.net"
port =                             8040
title =                            "we have the technology | magnetosphere electronic surplus"
languageCode =                     "en"
DefaultContentLanguage =           "en"
preserveTaxonomyNames =            true
ignoreErrors =                  [  "error-remote-getjson"]
disableHugoGeneratorInject =       true
enableRobotsTXT = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[params.copyright]
    name =                         "magnetosphere.net"
    name1 =                        "magnetosphereelectronicsurplus.com"
    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url =                          "https://magnetosphere.net"
    url1 =                         "https://magnetosphereelectronicsurplus.com"

    # Text to go before copyright information
    #prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"
    # Text to go between copyright and hugo disclaimer (if enabled)
    #suffix = "Example site"

[params]
    baseURL =                      "https://magnetosphere.net"
    sitetitle =                    "magnetosphere"
    title =                        "magnetosphere"
    titledesc =                    "electronic surplus"
    # The subtitle to display under the title in the home page
    # The name to display as main title in the home page
    mainpagetitle =                "<title>we have the technology | magnetosphere electronic surplus</title>"
    itemtitle =                    "<title>{{.Name}} | magnetosphere electronic surplus</title>"
    categorytitle =                "<title>{{$category}} | magnetosphere elctronic surplus</title>"
    categorydesc =                 "<meta name='description' content='Browse {{$table}} by category: {{$category}} page: {{$pagenumber}}. Credit Cards, Paypal, and Cryptocurrency accepted; buy with bitcoin or skycoin.'/>"
    #sitetitle = "<title>magnetosphere.net | we have the technology</title>"
    mainpagesubtitle =             "{{if eq $category ``}}we have the technology{{else}}{{if eq $subcategory ``}}{{$category}}{{else}}{{$subcategory}}{{end}}{{end}}"
    maintitle =                    "magnetosphere electronic surplus"
    # The description of your website. It will be displayed in the home page
    # The name to display in the copyright section in the footer
    copyrightname =                "magnetosphere.net magnetosphereelectronicsurplus.com"
    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl =                 "/"
    copyrightsuffix =              "all rights reserved"
    googlesiteverification =    [  "{{if eq $site `magnetosphere.net`}}",
                                   "<meta name='google-site-verification' content='yyNAbOUku-cKbCsko4BzXL5QhHb2SoO8r1KWJH37bF8' />",
                                   "{{end}}",
                                   "{{if eq $site `magnetosphereelectronicsurplus.com`}}",
                                   "<meta name='google-site-verification' content='2c_8zkofaYUQwXJXRBKrkkbU6pcmt7NqJc-CNI3yr9c' />",
                                   "{{end}}",
                                   ]

    end =                       [  "{{end}}"]
    else =                      [  "{{else}}"]



    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload =                 true
    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor =              1.0
    # Enables or disables the second flyby cursor. Default is false.
    loadonepass =                  false

[menu]
# This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier =                   "products"
    name =                         "Products"
    url =                          "/p/0"
    weight =                       5

  [[menu.main]]
    identifier =                   "about"
    name =                         "About"
    pre =                          "<span>"
    post =                         "</span>"
    url =                          "/about"
    weight = 10
  [[menu.main]]
    identifier =                   "policies"
    name =                         "Policies"
    pre =                          "<span>"
    post =                         "</span>"
    url =                          "/policy"
    weight =                       20
  [[menu.main]]
    identifier =                   "friend"
    name =                         "Friends"
    pre =                          "<span>"
    post =                         "</span>"
    url =                          "/friend"
    weight =                       30
  [[menu.main]]
    identifier =                   "blog"
    name =                         "Blog"
    pre =                          "<span>"
    post =                         "</span>"
    url =                          "/blog"
    weight =                       40
  [[menu.main]]
    identifier =                   "time"
    name =                         "{{$time}}"
    pre =                          "<span>"
    post =                         "</span>"
    url =                          ""
    weight =                       50
#  [[menu.main]]
#    identifier =                   "view"
#    name =                         "{{$view}}"
#    pre =                          "<span>"
#    post =                         "</span>"
#    url =                          ""
#    weight =                       60
