#################################
#[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "equipment"
    name = "Equipment"
    url = "/equipment"
    weight = 5

  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar


  [[menu.main]]
    identifier = "policies"
    name = "Policies"
    url = "/policy"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "friend"
    name = "Friends"
    url = "/friend"       # The path can lead to a content folder too.
    weight = 30

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"       # The path can lead to a content folder too.
    weight = 40


  #[[menu.main]]
  #  identifier = "bitcoin"
  #  name = "Bitcoin"
  #  url = "https://pay.magnetosphere.net/apps/42U8i51gFZF7reRf71hZ26wa7Qx3/pos/"       # The path can lead to a content folder too.
  #  weight = 40

  [[menu.main]]
    identifier = "time"
    name = "{{fdateMDY}}"
    url = ""       # The path can lead to a content folder too.
    weight = 50

  [[menu.main]]
    identifier = "snipcart1"
    name = "<span class=\"snipcart-checkout\">cart:<span class=\"snipcart-items-count\"></span> <span class=\"snipcart-total-price\"></span></span>"
    url = ""       # The path can lead to a content folder too.
    weight = 60


  [[menu.two]]
    identifier = 'main'
    name = 'Gallery'
    pre = ""
    url = '/'
    weight = -110
  [[menu.two]]
    name = 'Full List'
    post = ""
    pre = ""
    url = '/list'
    weight = -100
